Raw json:

{'hasError': True, 'errParameter': ['alluxio.underfs.s3.upload.threads.max', 'alluxio.user.network.rpc.max.connections'], 'reason': ["Value for 'alluxio.underfs.s3.upload.threads.max' should be a positive integer.", "Value for 'alluxio.user.network.rpc.max.connections' should be a positive integer."]}

{'hasError': True, 'errParameter': ['alluxio.underfs.s3.upload.threads.max', 'alluxio.user.network.rpc.max.connections'], 'reason': ["Value for 'alluxio.underfs.s3.upload.threads.max' should be a positive integer.", "Value for 'alluxio.user.network.rpc.max.connections' should be a positive integer."]}

{'hasError': True, 'errParameter': ['alluxio.underfs.s3.upload.threads.max', 'alluxio.user.network.rpc.max.connections'], 'reason': ["Value for 'alluxio.underfs.s3.upload.threads.max' should be a positive integer.", "Value for 'alluxio.user.network.rpc.max.connections' should be a positive integer."]}

Final result:

There are 2 misconfiguration parameters in the input: alluxio.underfs.s3.upload.threads.max	alluxio.user.network.rpc.max.connections
[Ciri] Reason for alluxio.underfs.s3.upload.threads.max: Value for 'alluxio.underfs.s3.upload.threads.max' should be a positive integer.
[Ciri] Reason for alluxio.user.network.rpc.max.connections: Value for 'alluxio.user.network.rpc.max.connections' should be a positive integer.
